server:
  port: 8441
  servlet:
    contextPath: /configserver

spring:
  application:
    name: ConfigRefreshServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mdtamim/ConfigRefreshServerTestApp
          repos:
            sampleRepo:
              pattern: ConfigRefreshClient
              searchPaths: 'src/main/resources'
              uri: https://github.com/mdtamim/SpringConfigClienApp
